[package]
name = "ths"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
tokio = { version = "1.4", features = ["full"] }
tokio-modbus = "0.16"
tokio-serial = "5.4.5"
tokio-stream = "0.1"
tracing = "0.1"

